### DISCUSSION TITLE
Schedule View: Changing fonts

### DISCUSSION THREAD

**Discussion by freqyfreqy** [YukiGasai/obsidian-google-calendar#108] [General]
Hi there! I have updated to the latest version with the changes discussed here in the pull request: https://github.com/YukiGasai/obsidian-google-calendar/pull/80

I was wondering how to change the font and size of these circled areas? I'm using the 'Style Settings' Plugin and can fonts from that plugin. You'll see in my screenshot that the time and the event description have different font sizes and I'm wondering where to tweak this. 

<img width="375" alt="image" src="https://user-images.githubusercontent.com/96843562/230166537-87ece1b0-6139-4651-b536-2cda2e32b9d2.png">

**Comment by YukiGasai** [comment]
Hi,
I never used the Style Settings plugin, but for the general Obsidian settings `Appearance` → `CSS Snippets` you can use this code.
```css
.gcal-schedule-time-container span {
	font-family: "Comic Sans MS", "Comic Sans", cursive;
	font-size: 99px !important;
}
.gcal-schedule-event-title {
	font-family: "Comic Sans MS", "Comic Sans", cursive;
	font-size: 99px !important
}
```
