### DISCUSSION TITLE
Set title of created note to GCal date

### DISCUSSION THREAD

**Discussion by mgorfer** [YukiGasai/obsidian-google-calendar#197] [Q&A] [answered]
I have a template `Templates/GCal-event-template.md` which works already pretty well.

```yaml
---
type: event
location: "{{gEvent.location}}"
date_all_day: "{{gEvent.start.date}}"
date_start: "{{gEvent.start.dateTime}}"
date_end: "{{gEvent.end.dateTime}}"
MOCs:
  - "[[Events MOC]]"
  - "[[<% tp.date.now('YYYY-MM-DD-dddd') %>]]"
summary:
---
<% await tp.file.move("/Extras/Events/" + tp.date.now("YYYY-MM-DD") + " " + tp.file.title) %>
# [[<% tp.date.now("YYYY-MM-DD") + " " + tp.file.title %>]]
{{gEvent.description}}
### Attendees
- [ ]
### Notes
-
```

Adding the following description to an event in my Google calendar, I specify creation folder and template.
```
Meeting my friends [[Friend A]] and [[Friend B]] for a tasty ramen
:Extras/Events-obsidian-GCal-event-template:
```

Uses my template and creates the following note with the tile `2023-09-24 Tasty Ramen`:
```yaml
event-id: 123456789
type: event
location: "Tasty Ramen Place"
date_all_day: ""
date_start: "2023-09-24T13:30:00+02:00"
date_end: "2023-09-24T14:30:00+02:00"
MOCs:
  - "[[Events MOC]]"
  - "[[2023-09-24-Sunday]]"
summary:
---
# [[2023-09-24 Tasty Ramen]]
Meeting my friends [[Friend A]] and [[Friend B]] for a tasty ramen
:Extras/Events-obsidian-GCal-event-template:
### Attendees
- [[]]
### Notes
-
```

I would like to just improve one thing.
1. Change the date of the created note, the linked MOC, and the Title to the GCal event date.

Is there an easy way for me to do that? And are there any other things which are missing in my template?
