### DISCUSSION TITLE
Change color and size of event in week view

### DISCUSSION THREAD

**Discussion by khanhuyengiang** [YukiGasai/obsidian-google-calendar#229] [Q&A]
Hi, thank you very much for the great plugin!
I want to ask how do I change color of the event in week view? In the styles.css file there are only dots colors for month view. 
Also how do I make the calendar longer? At the moment the event are squished together. 
Many thanks!

<img width="141" alt="image" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/92693446/819ff45f-ec5b-43f7-953d-d9ff6b8e2442">

**Comment by milk717** [comment]
I'm making and using css snipat myself to make the calendar prettier. Applying the snipat below will solve the problem.

```css
div.gcal-schedule-day-container.svelte-1whdazx {
    row-gap: 0.5em;
}

div.gcal-nav-container.svelte-oeb4qr {
    margin-top: 0.8em;
}

div.gcal-schedule-date-display.svelte-1whdazx {
    gap: 8px;
}

div.gcal-schedule-day-circle.svelte-1whdazx {
    border-radius: 0.5em;
    border: none;
    background-color: #f0f6f6;
}

div.today.svelte-1whdazx {
    background: #4285f4;
}

div.gcal-schedule-day-container.svelte-1whdazx {
    border-bottom: none;
    border: 1px solid #d9dadd;
    border-radius: 0.8em;
    padding: 8px;
}

button.gcal-nav-button {
    box-shadow: none;
    border: 1px solid #d9dadd;
}

button.gcal-new-event-button {
    box-shadow: none;
    border: 1px solid #d9dadd;
}

div.gcal-schedule-day-container.svelte-1whdazx {
    margin: 0.4em 0;
}

#calendar-container .day {
    padding: 0.5em 0;
}

#calendar-container .day,
#calendar-container .week-num {
    padding: 0.5em 0;
}

div.googleCalendarEvent.svelte-7dzwom {
    box-shadow: none;
}

div.googleCalendarEvent.svelte-2o273q {
    box-shadow: none;
}
```
