### ISSUE TITLE
Feature request: Strikethrough or remove past appointments in schedule view

### ISSUE THREAD

**Issue by andy-cowley** [YukiGasai/obsidian-google-calendar#153]
Current behaviour is a simple dynamic list, but it's difficult to see at a glance what is upcoming and what has passed. Having a strikethrough styling for events that have finished, or the option to hide finished events would be much better experience :)

**Comment by YukiGasai** [comment]
I added transparency to events that already happened.
If you want to use a strike-through, you can add this custom CSS:
```css
.gcal-schedule-pastEvent {
    text-decoration: line-through;
    opacity: 1 !important;
}
```
