### ISSUE TITLE
Disable recurrency symbol in scheduled view 

### ISSUE THREAD

**Issue by machado-t** [YukiGasai/obsidian-google-calendar#186]
I don't find this symbol useful and it kinda looks off centered in my vault.
Could it be optional or disabled somehow?

![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/111448902/a7329713-127a-4859-8634-3282ff502d4b)

**Comment by YukiGasai** [comment]
Hi,
you can add a custom CSS snipped under the Obsidian-Setting "Appearance" with the following code:

```css
.gcal-schedule-circle-container-recurring::after {
    display: none;
}
```
