### ISSUE TITLE
Showcase of my css snippets for this plugin and question about spacing of nav element vs Timeline in sidebar

### ISSUE THREAD

**Issue by matyasLevinsky** [YukiGasai/obsidian-google-calendar#253]
Hi, 
First of all thank you for this plugin, it is very useful.  I am mainly using it in my right sidebar, as a TimelineView. The real estate of the sidebar is limited so i grew really annoyed at wasted space, especially between the navigation and the actual timeline.  I have some surface level knowledge of css so I tried to make some snippets to fix that issue. 

I also have a question to someone who can use the developer tools of obsidian better than me: Why is there still a gap/padding/margin between the elements `<div class="gcal-title-container">` and `<div class="gcal-week-container svelte-m4uap8" style="grid-template-columns: auto repeat(1, minmax(0px, 1fr));">` even though the inspect tool shows there to be none? It is driving me crazy. To replicate just open obsidian developer tools, `Ctrl+Shift+I` and go down the rabbit hole, its not margins, padding or border. **What is it? -** It's driving me crazy.  

I would like to add these examples to the [User Examples](https://yukigasai.github.io/obsidian-google-calendar/Examples/UserExamples) page, after someone confirms they are not dangerous, or achievable in a more intuitive manner. 

These are my modifications:
1. Remove padding for nav (set to 0) and add minimal margin on top to prevent stacking:
```css
.gcal-nav-container.svelte-oeb4qr {
	margin-bottom:0; /* was 1em */
	margin-top:3px, /* was 0 */
}
```
2. Remove padding for date container: (set to 0)
```css
.gcal-date-container.svelte-oeb4qr {
	margin-bottom:0; /* was 10px */
}
```
3. Set the current time line length to 100%:
```css
.gcal-time-display.svelte-1b16v0k {
    position: absolute;
    width: 100%; /* was 95% */
    height: 3px; 
    background: red;
    overflow: visible;
    z-index: 2;
}
```
4. Goal for minimal buttons
Goal: `<< < Today > >>`
This selects only buttons within `.gcal-nav-container`:
```css
.gcal-nav-container button {  
    padding: 1px 6px; /*there are other properties, not mentioned here*/  
}
```
6. Adjust top padding, as lines are shifted:
```css
.gcal-timeline.svelte-1b16v0k {
    position: relative;
    display: flex;
    flex-direction: row;
    padding-top: 0px; /* Was 5px, Number adjustment, so they line up with the lines */
    flex-shrink: 1000;
    min-height: 0;
    margin: -199.2px 0px 0px 0px !important; /* was -208.167px 0px 0px 0px */
}
```
7. Make internal padding thinner:
```css 
.gcal-week-container.svelte-m4uap8.svelte-m4uap8 {
    position: relative;
    display: inline-grid;
    gap: 9px; /* was 16px */
    grid-auto-flow: row;
    overflow: hidden;
}
```
Change images:
**Before:**
![Pasted image 20240409225450](https://github.com/YukiGasai/obsidian-google-calendar/assets/114734990/b47409db-dde3-40a3-af71-e43fd5b2afee)
**After:**
![Pasted image 20240410001115](https://github.com/YukiGasai/obsidian-google-calendar/assets/114734990/7aca32a6-64a1-4ff7-80bf-22cfafb07e62)
