### ISSUE TITLE
Mapping issues using time properties

### ISSUE THREAD

**Issue by cagechi** [YukiGasai/obsidian-google-calendar#305]
I am using `Create gCal Event from Frontmatter` from a note created with Full calendar plugin.
Succeeds when `All day event`, but fails when time is specified.

Sample note (When Successl)
```
---
title: TEST
allDay: true
date: 2025-02-25
completed: 
mapping: Mapping.md
---
```

Sample note (When Failed)
```
---
title: TEST
allDay: false
date: 2025-02-25
completed: 
mapping: Mapping.md
startTime: 18:00
endTime: 19:00
---
```

Mapping.md
```
---
mapping:
  title: summary
  date: start.date
  startTime: start.dateTime
  endTime: end.dateTime
---
```

Console
![Image](https://github.com/user-attachments/assets/eb9c4f30-e24f-4211-9d90-7d218a53fd5b)
