### ISSUE TITLE
Change background color or give possibility to change the background color's opacity

### ISSUE THREAD

**Issue by Rhydderch** [YukiGasai/obsidian-google-calendar#37]
Hello,

I love your plugin, thank you for making it.
I am using a new theme and the colors of the calendar really pop out too much:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/3197629/209926407-bb5daec3-2b42-4a4d-a71c-475bdae3cac9.png">

Would it be possible to give the option to the user to either set the opacity of the background or set custom colors for each calendar?

With CSS I can modify the opacity, but it also affects the text:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/3197629/209926745-5a9e6c73-d48b-466c-a648-6ec727e83b91.png">

**Comment by YukiGasai** [comment]
Hi @Rhydderch,
I think trying to create settings for this is too complex.
The way to add some custom CSS is the best way.
I added some extra classes and added a span to keep the text visible.

For the div(background):
```
googleCalendarEvent
googleCalendarEvent_Calendar_Color_{calendar.colorId}
googleCalendarEvent_Event_Color_{event.colorId} (defaults to undefined)
googleCalendarEvent_Id_{calendar.id}
```

For the span(text):
```
googleCalendarName
googleCalendarName_Calendar_Color_{calendar.colorId}
googleCalendarName_Event_Color_{event.colorId} (defaults to undefined)
googleCalendarName_Id_{calendar.id}
```

**Comment by Rhydderch** [comment]
Awesome, thanks!

I was able to customize the CSS to my liking:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/3197629/211611784-a7ae55e1-fe87-4dd9-beb9-1959a8c207c3.png">

```css
.titleContainer button{
    border: 1px solid var(--text-muted);
    box-shadow: none;
    width:10px;
    height:10px;
    padding:10px;
    color:var(--text-muted);
    background-color: transparent;
}

.navigationContainer {
    margin-top:10px;
}

.navigationContainer button{
    border: 1px solid var(--text-muted);
    box-shadow: none;
    color:var(--text-muted);
    padding:10px;
    max-height:20px;
    background-color: transparent;
}

.titleContainer h3{
    margin-left:10px;
    margin-top:0px;
    font-size:1.2em;
    color:var(--text-muted) !important;
}

.timeline {
    margin-left:3px;
}


.timeline .event, .googleCalendarEvent{
    box-shadow: none;
    padding:0px;
    padding-left:5px;
    /*background:rgba(220, 220, 220, 0.3) !important;*/
    background-image: linear-gradient(rgb(245 245 245/75%) 0 0) !important;
    color:var(--text-normal);
    font-weight: 600;
    
    border:1px solid var(--text-muted);
    border-left:1px solid var(--text-muted);
    
    border-radius: 6px !important;
}

.googleCalendarName {
    padding:0px;
    margin:0px;
    font-size:1.5em;
    display: inline-block;
    margin:auto;
    margin-top:-4px;
}


.hourTextContainer .hourText  {
    color:var(--text-muted);
    text-align: right;
    font-size:0.9em !important;
}

.hourTextContainer{
    margin-top:-10px !important;
   
}

.hourLine::after {
    content: "";
    position: absolute;
    width: 95% !important;
    left: 25px !important;
    border-bottom: 1px solid var(--text-faint) !important;
}
```
