### ISSUE TITLE
Event from “Create Google Calendar Event from frontmatter” sets the date to the day after the date in the frontmatter

### ISSUE THREAD

**Issue by AngelusDomini** [YukiGasai/obsidian-google-calendar#61]
Hello! I noticed that when I use the “Create Google Calendar Event from frontmatter” command, the event is indeed created but it gets set for the day after the date indicated in the front matter. For example, I have the frontmatter of a note like this:

```
mapping:
  title: summary
  deadline: start.date
title: Event Title
deadline: 2023-02-03
```

When I do the command, instead of the event being set on February 3, it gets set on February 4.
